name: rixa
description: Creating the application skeleton could be tough and time taking. Rixa is the easiest and simplest way to design your application
version: 0.3.6
homepage: https://github.com/FlutterWay/rixa

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  internet_connection_checker_plus: ^1.0.1
  crop_your_image: ^0.7.4
  flutter_advanced_avatar: ^1.2.0
  video_player: ^2.6.1
  matrix4_transform: ^2.0.1
  boxicons: ^2.1.3
  markdown: ^7.0.2
  html: ^0.15.2
  bubble_tab_indicator: ^0.1.6
  flick_video_player: ^0.5.0
  extended_image: ^8.0.1
  dart_vlc: ^0.4.0
  google_fonts: ^4.0.3
  go_router: ^7.1.1
  flutter_persistent_keyboard_height: ^1.0.5
  flutter_keyboard_size: ^1.0.1
  provider: ^6.0.5
  platform_info: ^3.2.0
  flutter_highlight: ^0.7.0
  shared_preferences: ^2.1.0
  flutter_emoji_gif_picker: ^0.1.3
  file_picker: ^5.2.7
  markdown_widget: ^2.1.0
  flutter_math_fork: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
